export const employees = [
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
];
