export const employees = [
  {
    id: 1,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 2,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 3,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 4,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 5,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 6,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 7,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 8,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 9,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 9,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 10,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 11,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 12,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 13,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 14,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 15,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 16,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 17,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 18,
    name: "John Doe",
    department: "Testing",
    available: true,
    gender: "male",
    designation: "Frontend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 19,
    name: "Peter Doe",
    department: "Deployment",
    available: false,
    gender: "male",
    designation: "Backend Developer",
    joiningDate: "2020-01-01",
  },
  {
    id: 20,
    name: "Olivia Doe",
    department: "Deployment",
    available: true,
    gender: "Female",
    designation: "Full Stack Developer",
    joiningDate: "2020-01-01",
  },
];
